name: vaultenv
version: 0.6.0
synopsis: Runs processes with secrets from HashiCorp Vault
license: BSD3
github: channable/vaultenv

executables:
  vaultenv:
    main: Main.hs
    source-dirs: app
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -Wall -Werror
    dependencies:
      - base < 5
      - async
      - bytestring
      - connection
      - containers
      - http-conduit
      - http-client
      - lens
      - lens-aeson
      - optparse-applicative
      - retry
      - text
      - unordered-containers
      - unix
      - utf8-string
      - mtl
