name: vaultenv
version: 0.7.1
synopsis: Runs processes with secrets from HashiCorp Vault
license: BSD3
github: channable/vaultenv

dependencies:
  - base
  - async
  - bytestring
  - connection
  - containers
  - http-conduit
  - http-client
  - lens
  - lens-aeson
  - megaparsec
  - mtl
  - optparse-applicative
  - parser-combinators
  - retry
  - text
  - unordered-containers
  - unix
  - utf8-string
  - optparse-applicative

    #ghc-options: -Wall -Werror

library:
  source-dirs: src

executables:
  vaultenv:
    main: Main.hs
    source-dirs: app
    dependencies:
      - vaultenv

tests:
  vaultenv-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vaultenv
    - hspec
    - hspec-discover
    - hspec-expectations
    - directory
